version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Dead code detection (replaces deprecated deadcode and varcheck)
    - unused
    # Detects unused assignments
    - ineffassign
    # Static analysis
    - staticcheck

formatters:
  enable:
    # Import formatting
    - goimports
